// All these languages are over 16 characters long.
// We need to handle them differently
const longLanguageNames: string[] = [
    "Adobe Font Metrics",
    "Apollo Guidance Computer",
    "Closure Templates",
    "Cloud Firestore Security Rules",
    "Common Workflow Language",
    "DIGITAL Command Language",
    "Edje Data Collection",
    "Fortran Free Form",
    "GCC Machine Description",
    "Game Maker Language",
    "Glyph Bitmap Distribution Format",
    "Grammatical Framework",
    "Graph Modeling Language",
    "Groovy Server Pages",
    "JSON with Comments",
    "Java Server Pages",
    "KiCad Legacy Layout",
    "Linux Kernel Module",
    "Literate CoffeeScript",
    "Microsoft Developer Studio Project",
    "Microsoft Visual Studio Solution",
    "Module Management System",
    "Motorola 68K Assembly",
    "Object Data Instance Notation",
    "Open Policy Agent",
    "OpenStep Property List",
    "OpenType Feature File",
    "Parrot Internal Representation",
    "Regular Expression",
    "Spline Font Database",
    "TextMate Properties",
    "Unified Parallel C",
    "Valve Data Format",
    "Visual Basic .NET",
    "Wavefront Material",
    "Web Ontology Language",
    "Windows Registry Entries",
    "World of Warcraft Addon Data",
    "X Font Directory Index",
    "XML Property List",
];

export default longLanguageNames;
